name: "CHORE: 환경/설정/정리"
description: 기능 변경 없이 환경 설정, 정리, 삭제 등 내부 작업을 위한 Pull Request입니다.
title: "[CHORE] "
labels: ["chore"]
body:
  - type: input
    id: summary
    attributes:
      label: 🔧 요약
      description: 어떤 작업을 했는지 간단하게 설명해주세요
      placeholder: 예) Spring Boot 3.2 업그레이드 및 의존성 정리
    validations:
      required: true

  - type: input
    id: issue_link
    attributes:
      label: 🔗 관련 이슈
      description: 관련된 이슈 번호를 입력해주세요
      placeholder: 예) #123
    validations:
      required: false

  - type: dropdown
    id: type
    attributes:
      label: 📂 작업 유형
      description: 어떤 종류의 작업인가요?
      options:
        - 의존성 업데이트
        - 설정/환경 변경
        - 불필요한 코드/파일 삭제
        - CI/CD 수정
        - 기타 메타 작업
    validations:
      required: true

  - type: textarea
    id: changes
    attributes:
      label: 📝 변경 내용
      description: 구체적인 변경 사항을 나열해주세요
      placeholder: |
        - Spring Boot 2.7.x → 3.2.x 업그레이드
        - javax.* → jakarta.* 패키지 마이그레이션
        - Gradle 7.6 → 8.5 업그레이드
        - 사용하지 않는 의존성 제거 (5개)
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: 📌 영향 범위
      description: 이 변경이 개발/배포/CI 등에 미치는 영향을 설명해주세요
      placeholder: |
        - JDK 17 이상 필수
        - 빌드 시간 약 20% 단축 예상
        - 모든 import 문 수정 필요
        - 기존 기능에는 영향 없음
    validations:
      required: false

  - type: textarea
    id: migration
    attributes:
      label: 🔄 마이그레이션 가이드
      description: 다른 개발자를 위한 마이그레이션 가이드 (필요 시)
      placeholder: |
        1. JDK 17 설치
        2. IDE import cache 초기화
        3. gradle clean build 실행
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 체크리스트
      description: PR 제출 전 확인사항
      options:
        - label: 로컬에서 변경 사항 테스트 완료
          required: true
        - label: CI/CD 파이프라인 정상 동작 확인
          required: true
        - label: 기존 기능 영향 없음 확인
        - label: 팀원에게 공유 필요한 사항 문서화
        - label: 릴리즈 노트 작성 필요 여부 확인

  - type: textarea
    id: additional_info
    attributes:
      label: 📚 추가 정보
      description: 기타 참고사항이나 배경 정보
      placeholder: 추가적으로 전달하고 싶은 내용이 있다면 작성해주세요
    validations:
      required: false