name: "TEST: 테스트 추가"
description: 테스트 코드 추가를 위한 Pull Request입니다.
title: "[TEST] "
labels: ["test"]
body:
  - type: input
    id: summary
    attributes:
      label: 🧪 요약
      description: 추가한 테스트에 대해 간단하게 설명해주세요
      placeholder: 예) UserService 단위 테스트 추가
    validations:
      required: true

  - type: input
    id: issue_link
    attributes:
      label: 🔗 관련 이슈
      description: 관련된 이슈 번호를 입력해주세요
      placeholder: 예) #123
    validations:
      required: false

  - type: dropdown
    id: test_type
    attributes:
      label: 📋 테스트 유형
      description: 어떤 종류의 테스트인가요?
      options:
        - 단위 테스트 (Unit Test)
        - 통합 테스트 (Integration Test)
        - E2E 테스트 (End-to-End Test)
        - 성능 테스트 (Performance Test)
        - 보안 테스트 (Security Test)
    validations:
      required: true

  - type: textarea
    id: target
    attributes:
      label: 🎯 테스트 대상
      description: 테스트한 코드/기능을 설명해주세요
      placeholder: |
        - 대상 클래스/메서드: UserService.createUser()
        - 테스트 시나리오: 유효한 사용자 생성, 중복 이메일 검증, 필수 필드 누락
        - 모킹 전략: UserRepository는 Mock 사용
    validations:
      required: true

  - type: textarea
    id: test_cases
    attributes:
      label: 📑 테스트 케이스
      description: 추가한 테스트 케이스를 나열해주세요
      placeholder: |
        - ✅ 정상적인 사용자 생성 테스트
        - ✅ 중복 이메일 예외 처리 테스트
        - ✅ 필수 필드 누락 시 예외 테스트
        - ✅ 비밀번호 유효성 검증 테스트
    validations:
      required: true

  - type: textarea
    id: coverage
    attributes:
      label: 📊 커버리지 변화
      description: 테스트 커버리지 변화를 설명해주세요
      placeholder: |
        - 이전 커버리지: 65%
        - 현재 커버리지: 78%
        - 커버되지 않은 주요 부분: 예외 처리 로직
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 체크리스트
      description: PR 제출 전 확인사항
      options:
        - label: 모든 테스트가 통과함
          required: true
        - label: 테스트 코드 리뷰 완료
          required: true
        - label: CI/CD 파이프라인에서 정상 동작
        - label: 테스트 커버리지 목표 달성
        - label: 테스트 문서 업데이트 (필요시)

  - type: textarea
    id: additional_info
    attributes:
      label: 📚 추가 정보
      description: 기타 참고사항이나 배경 정보
      placeholder: 추가적으로 전달하고 싶은 내용이 있다면 작성해주세요
    validations:
      required: false